DROP TABLE IF EXISTS task CASCADE;
DROP TABLE IF EXISTS todolist CASCADE;
CREATE TABLE task (
	task_id integer generated by default as identity,
	name varchar(255) not null,
	fk_todolist_id integer,
	primary key (task_id)
);
CREATE TABLE todolist (
	todolist_id integer generated by default as identity,
	name varchar(255),
	primary key (todolist_id)
);
ALTER TABLE task add constraint UK_8qrhl5wlohdjoko9nrorkdjkp unique (name);
ALTER TABLE todolist add constraint UK_9ome4qyhbd8a1n39dvjsxjks0 unique (name);
ALTER TABLE task add constraint FKdtss7ab4sx4oagfqyacono43a foreign key (fk_todolist_id) references todolist on delete cascade;